name: Java build
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      test-coverage:
        required: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven
      - name: Maven
        run: |
          COVERAGE_GOAL=
          if [ $TEST_COVERAGE == 'true'; then
            # JaCoCo phase is needed to create code coverage report that will be later uploaded to Codecov.
            COVERAGE_GOAL=jacoco:report
          fi
          # GPG must be skipped, because CI server does not have release GPG key.
          # Failure on javadoc warnings is enabled only in CI builds,
          # so that warnings specific to one JDK version do not break independent builds.
          # Printing maven version (-V) helps diagnose CI-specific build behavior.
          mvn install $COVERAGE_GOAL -Dgpg.skip=true -Dmaven.javadoc.failOnWarnings=true -B -V
        env:
          TEST_COVERAGE: ${{ inputs.test-coverage }}
      - uses: codecov/codecov-action@v2
        if: ${{ inputs.test-coverage }}
