name: Java release
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
    secrets:
      server-password:
        required: true
        type: string
      signing-key:
        required: true
        type: string
      signing-password:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          server-id: ossrh
          server-username: MAVEN_SERVER_USERNAME
          server-password: MAVEN_SERVER_PASSWORD
          gpg-private-key: ${{ secrets.signing-key }}
          gpg-passphrase: MAVEN_SIGNING_PASSWORD
          cache: maven
      - name: Maven
        # Printing maven version (-V) helps diagnose GitHub-specific build behavior.
        run: mvn -B -V deploy
        env:
          MAVEN_SERVER_USERNAME: robertvazan
          MAVEN_SERVER_PASSWORD: ${{ secrets.server-password }}
          MAVEN_SIGNING_PASSWORD: ${{ secrets.signing-password }}
